
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/mnt/programs/Apps/clion-2024.2.3/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.9.3-76060903-generic - x86_64
...
